# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    value: '123'
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
      - uses: actions/checkout@v3
        with:
          name: Eve-ning/osu-view
          submodules: 'true'

      - name: Runs Project
        working-directory: projects/sr-calc/
        shell: bash
        run: |
          chmod +x ./run.sh
          ./run.sh mytest << EOF
          1
          EOF

      - name: Assert Essential Project Files exist
        shell: bash
        run: |
          if [ ! -f osu.view/sr-calc/mytest/nt.results.json ]; then
            echo Missing expected nt.results.json 
            exit 1
          fi

      - uses: actions/upload-artifact@v3
        shell: bash
        with:
          name: SR Calculation Results
          path: osu.view/sr-calc/mytest/

#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.who-to-greet }}
