# action.yml
name: 'Recalculate osu! SR'
description: 'Recalculate osu! SR for maps given branches and query'
inputs:
  db-url:  # id of input
    description: 'osu! Database URL'
    required: true
    default: 'test-for-fail'
runs:
  using: 'composite'
  steps:
      - uses: actions/checkout@v3
        with:
          repository: Eve-ning/osu-view
          submodules: 'true'
      - run: |
          cd projects/sr-calc/
          chmod +x ./run.sh
          sed -ie '/DB_URL=/s@=.*@=${{ inputs.db-url }}@' .env
          ./run.sh mytest << EOF
          1
          EOF
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: SR Calculation Results
          path: osu.view/sr-calc/mytest/

#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.who-to-greet }}
