# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    value: '123'
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - run: |
        echo 1 >> test.txt
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: test artifact
        path: test.txt
#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.who-to-greet }}
