name: 'Recalculate osu! SR'
description: 'Recalculate osu! SR for maps given branches and query'
inputs:
  db-url:
    description: 'osu! Database URL'
    required: true
    default: 'https://github.com/Eve-ning/osu-data-docker/raw/master/rsc/YYYY_MM_DD_performance_mania_top_1000.tar.bz2'
  files-url:
    description: 'osu! Files URL'
    required: true
    default: 'https://github.com/Eve-ning/osu-data-docker/raw/master/rsc/YYYY_MM_DD_osu_files.tar.bz2'
  files-sql-query:
    description: 'Query for the SQL Files. Must start with SELECT beatmap_id FROM osu_beatmaps'
    required: true
    default: 'SELECT beatmap_id FROM osu_beatmaps WHERE playmode=3 AND approved=1 AND difficultyrating>7 LIMIT 25'
  osu-git:
    description: 'osu repository link'
    required: true
    default: 'https://github.com/ppy/osu'
  osu-git-branch:
    description: 'osu repository branch'
    required: true
    default: 'master'
  osu-tools-git:
    description: 'osu-tools repository link'
    required: true
    default: 'https://github.com/ppy/osu-tools'
  osu-tools-git-branch:
    description: 'osu-tools repository branch'
    required: true
    default: 'master'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: Eve-ning/osu-view
#        ref: '0b1f82c885adbd8560a02ffbf9aebc1de7d16a30'
        submodules: 'true'
    - run: |
        cd projects/sr-calc/
        chmod +x ./run.sh
        ./run.sh -y "${{ inputs.db-url }}" \
             -z "${{ inputs.files-url }}" \
             -q "${{ inputs.files-sql-query }}" \
             -o "${{ inputs.osu-git }}" \
             -o "${{ inputs.osu-git-branch }}" \
             -t "${{ inputs.osu-tools-git }}" \
             -t "${{ inputs.osu-tools-git-branch }}" << EOF
        1
        EOF
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: SR Calculation Results
        path: osu.view/sr-calc
