# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    value: '123'
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
      - uses: actions/checkout@v3
        with:
          repository: Eve-ning/osu-view
          submodules: 'true'

      - run: |
          cd projects/sr-calc/
          chmod +x ./run.sh
          ./run.sh mytest << EOF
          1
          EOF
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: SR Calculation Results
          path: osu.view/sr-calc/mytest/

#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.who-to-greet }}
