on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Eve-ning/osu-view-sr-calc@v0.10
        with:
          db-url: 'test-for-fail'
